# Generated by Django 5.2.4 on 2025-10-04 07:57

import charities.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefactor",
            name="experience",
            field=models.SmallIntegerField(
                choices=[(0, "Beginner"), (1, "Intermediate"), (2, "Expert")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="reg_number",
            field=models.CharField(
                max_length=10, validators=[charities.validators.RegNumberValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_benefactor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="charities.benefactor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="gender_limit",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("MF", "Unset")],
                default="MF",
                max_length=2,
            ),
        ),
    ]
