# Generated by Django 5.2.4 on 2025-10-04 07:44

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("MF", "Unset")],
                default="MF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[accounts.validators.PhoneValidator()],
            ),
        ),
    ]
